//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class eCommerceCS : DbContext
    {
        public eCommerceCS()
            : base("name=eCommerceCS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<ProductMaster> ProductMaster { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderItem> OrderItem { get; set; }
    
        public virtual ObjectResult<Nullable<int>> PR_Cart_CheckIteamSelectByID(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PR_Cart_CheckIteamSelectByID", productIDParameter);
        }
    
        public virtual int PR_Cart_InsertProduct(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_Cart_InsertProduct", productIDParameter);
        }
    
        public virtual int PR_Cart_TruncateData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_Cart_TruncateData");
        }
    
        public virtual int PR_CartDeleteItem_SelectByPK(Nullable<int> cartID)
        {
            var cartIDParameter = cartID.HasValue ?
                new ObjectParameter("CartID", cartID) :
                new ObjectParameter("CartID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CartDeleteItem_SelectByPK", cartIDParameter);
        }
    
        public virtual ObjectResult<PR_CartItemShow_SelectAll_Result> PR_CartItemShow_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_CartItemShow_SelectAll_Result>("PR_CartItemShow_SelectAll");
        }
    
        public virtual int PR_CheckOut_Insert(Nullable<int> productID, Nullable<int> orderQuantity, Nullable<decimal> totalBill)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var orderQuantityParameter = orderQuantity.HasValue ?
                new ObjectParameter("OrderQuantity", orderQuantity) :
                new ObjectParameter("OrderQuantity", typeof(int));
    
            var totalBillParameter = totalBill.HasValue ?
                new ObjectParameter("TotalBill", totalBill) :
                new ObjectParameter("TotalBill", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CheckOut_Insert", productIDParameter, orderQuantityParameter, totalBillParameter);
        }
    
        public virtual int PR_CustomerConfiramOrder_Insert(string firstName, string lastName, string address, Nullable<int> productID, Nullable<int> orderQuantity, Nullable<decimal> totalBill)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var orderQuantityParameter = orderQuantity.HasValue ?
                new ObjectParameter("OrderQuantity", orderQuantity) :
                new ObjectParameter("OrderQuantity", typeof(int));
    
            var totalBillParameter = totalBill.HasValue ?
                new ObjectParameter("TotalBill", totalBill) :
                new ObjectParameter("TotalBill", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CustomerConfiramOrder_Insert", firstNameParameter, lastNameParameter, addressParameter, productIDParameter, orderQuantityParameter, totalBillParameter);
        }
    
        public virtual ObjectResult<PR_CustomerOrderList_SelectAll_Result> PR_CustomerOrderList_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_CustomerOrderList_SelectAll_Result>("PR_CustomerOrderList_SelectAll");
        }
    
        public virtual int PR_ProductMaster_DeleteByPK(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ProductMaster_DeleteByPK", productIDParameter);
        }
    
        public virtual ObjectResult<PR_ProductMaster_GetProductNamePriceSelectAll_Result> PR_ProductMaster_GetProductNamePriceSelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ProductMaster_GetProductNamePriceSelectAll_Result>("PR_ProductMaster_GetProductNamePriceSelectAll");
        }
    
        public virtual int PR_ProductMaster_Insert(string productName, Nullable<int> productQuntity, string productDetails, Nullable<decimal> productPrice, string productImage)
        {
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productQuntityParameter = productQuntity.HasValue ?
                new ObjectParameter("ProductQuntity", productQuntity) :
                new ObjectParameter("ProductQuntity", typeof(int));
    
            var productDetailsParameter = productDetails != null ?
                new ObjectParameter("ProductDetails", productDetails) :
                new ObjectParameter("ProductDetails", typeof(string));
    
            var productPriceParameter = productPrice.HasValue ?
                new ObjectParameter("ProductPrice", productPrice) :
                new ObjectParameter("ProductPrice", typeof(decimal));
    
            var productImageParameter = productImage != null ?
                new ObjectParameter("ProductImage", productImage) :
                new ObjectParameter("ProductImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ProductMaster_Insert", productNameParameter, productQuntityParameter, productDetailsParameter, productPriceParameter, productImageParameter);
        }
    
        public virtual ObjectResult<PR_ProductMaster_SelectAll_Result> PR_ProductMaster_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ProductMaster_SelectAll_Result>("PR_ProductMaster_SelectAll");
        }
    
        public virtual ObjectResult<PR_ProductMaster_SelectByPK_Result> PR_ProductMaster_SelectByPK(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ProductMaster_SelectByPK_Result>("PR_ProductMaster_SelectByPK", productIDParameter);
        }
    
        public virtual int PR_ProductMaster_UpdateByPK(Nullable<int> productID, string productName, Nullable<int> productQuntity, string productDetails, Nullable<decimal> productPrice, string productImage)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productQuntityParameter = productQuntity.HasValue ?
                new ObjectParameter("ProductQuntity", productQuntity) :
                new ObjectParameter("ProductQuntity", typeof(int));
    
            var productDetailsParameter = productDetails != null ?
                new ObjectParameter("ProductDetails", productDetails) :
                new ObjectParameter("ProductDetails", typeof(string));
    
            var productPriceParameter = productPrice.HasValue ?
                new ObjectParameter("ProductPrice", productPrice) :
                new ObjectParameter("ProductPrice", typeof(decimal));
    
            var productImageParameter = productImage != null ?
                new ObjectParameter("ProductImage", productImage) :
                new ObjectParameter("ProductImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ProductMaster_UpdateByPK", productIDParameter, productNameParameter, productQuntityParameter, productDetailsParameter, productPriceParameter, productImageParameter);
        }
    
        public virtual ObjectResult<PR_ProductMasterShowDetails_SelectByPK_Result> PR_ProductMasterShowDetails_SelectByPK(Nullable<int> productID)
        {
            var productIDParameter = productID.HasValue ?
                new ObjectParameter("ProductID", productID) :
                new ObjectParameter("ProductID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ProductMasterShowDetails_SelectByPK_Result>("PR_ProductMasterShowDetails_SelectByPK", productIDParameter);
        }
    
        public virtual ObjectResult<PR_ShowProducts_SelectAll_Result> PR_ShowProducts_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ShowProducts_SelectAll_Result>("PR_ShowProducts_SelectAll");
        }
    }
}
